services:
  # Servicio Redis
  - type: redis
    name: redis
    ipAllowList: []
    plan: free

  # API FastAPI
  - type: web
    name: api
    runtime: docker
    dockerContext: ./api
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    #branch: main
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: PORT
        value: 8000
    healthCheckPath: /health

 # Frontend como web service con nginx
  - type: web
    name: web
    runtime: static
    buildCommand: ""
    staticPublishPath: ./web